apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: petisgone-com-tls
spec:
  secretName: petisgone-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: petisgone.com
  dnsNames:
    - petisgone.com
    - www.petisgone.com
